Package:ragnarok-srv
Version:0.0.1
Section: system
Priority: optional
Architecture: all
Depends: bash
Maintainer: White Wolf Team
Description: Server to deal with ragnarok client.
Homepage: github.com/white-wolf-project
